### PR TITLE
Read Directly From Cloud Functionality

### PR DESCRIPTION
**Pull request by ctuguinay**
### Read Directly From Cloud Functionality (On Hold)

This PR addresses #69:

- Functionality to read from .evl and .evr files from the cloud.
- No tests yet and no information regarding any S3 buckets and such.

**Note**:
Currently on hold. Will wait for Wu-Jung and Valentina to come back to continue work on this.

### CODE REVIEW

**Review by leewujung — COMMENTED** [review]
I think that rather than having separate functions for reading cloud files, we can have optional input argument `storage_options` to the existing `read_evl` and `read_evr` functions (see [this example from echopype](https://github.com/OSOceanAcoustics/echopype/blob/80cec02795f5ac42100acc7d00a5ab5457c854d7/echopype/convert/api.py#L316)) for the credentials, and have the input path accepting both local and cloud paths.

In terms of testing, in echopype we actually test with a docker-minio server that simulates s3 functions, so that we do not rely on external sources for testing. I think we can delay the CI testing to later and just make sure the functionalities work when we use it, and circle back when we have more time to add that testing infrastructure back in.

**Comment by leewujung** [comment]
Also I think we can push this to be something added at v0.1.1 (ie. not at the first release).

**Comment by ctuguinay** [comment]
@leewujung Oh I just took a look at the echopype implementation and it does look a lot cleaner. After I put some last touches on a draft PR for testing, I'll be waiting for Valentina to review my 2d 3d mask PR again and within transect mask PR before I can start anything else. I could probably start working on this in the meantime. I don't think it's too much to implement, if I don't implement the docker test.

**Comment by leewujung** [comment]
Sounds good!

**Pull request closed without merging**
